version: '3.8'

services:
  book-service:
    env_file:
      - .env.local
    build:
      context: .
    container_name: rest-server
    # Name for app container
    hostname: rest-server
    ports:
      - 80:8080
    environment:
      - HTTP_PORT=${HTTP_PORT:-8080}
    deploy:
      restart_policy:
        condition: on-failure
